import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class DatiService {
  constructor() { }
  mostre=[
    {nome:"MOSTRA DI DE NITTIS A MILANO",artisti:"Giuseppe De Nittis",immagine:"https://www.artribune.com/wp-content/uploads/2024/02/Giuseppe-De-Nittis-Lamazzone-al-Bois-de-Boulogne-1875-ca-Museo-delle-Raccolte-Frugone-Genova.jpg", descrizione:"La mostra di Giuseppe De Nittis a Palazzo Reale di Milano sarà un viaggio nella pittura di uno dei più grandi artisti italiani dell’Ottocento, particolarmente sensibile alle correnti del Verismo e dell’Impressionismo che seppe interpretare in chiave originale e personale.", dataInizio:"2024/02/24", dataFine:"2024/06/30"},
    {nome:"MOSTRA DI MARTIN PARR A MILANO",artisti:"Martin Parr",immagine:"https://fotocult.it/wp-content/uploads/2024/03/Martin-Parr-2.jpg", descrizione:"La mostra Martin Parr, Short & Sweet a Milano, frutto della rinnovata collaborazione con Magnum Photos, celebra il lavoro del fotoreporter britannico che ha saputo indagare la società nei suoi aspetti più controversi con un tocco di ironia e vivacità.", dataInzio:"2024/02/10", dataFine:"2024/06/30"},
    {nome:"TATUAGGIO. STORIE DAL MEDITERRANEO",artisti:"diversi tatuatori di piu' epoche",immagine:"https://d2j6dbq0eux0bg.cloudfront.net/images/4871051/4225084249.jpg", descrizione:"La mostra 'Tatuaggio. Storie dal Mediterraneo' al Mudec di Milano, è un percorso curioso alla scoperta di una pratica dalla storia millenaria, che ha attraversato i secoli e i continenti, arricchendosi di nuovi significati e di diverse modalità di realizzazione.", dataInzio:"2024/03/28", dataFine:"2024/07/28"},
    {nome:"MOSTRA JOAN MIRÒ. LA POESIA DELLE FORME A MONZA",artisti:"Joan Miro",immagine:"https://www.amartemoderna.com/wp-content/uploads/2017/05/mir.jpg.webp", descrizione:"La visita guidata alla mostra di Mirò a Monza sarà un'occasione per ripercorrere l'arte colorata, originale e sognante di uno dei maggiori artisti del XX secolo. Organizzata in occasione del 130° anniversario della nascita dell'artista catalano Joan Mirò, la Villa Reale di Monza ospita al suggestivo terzo piano del Belvedere, la mostra 'La poesia delle forme', dedicata al raffinato e complesso rapporto tra arte e parola che caratterizzò l'opera di Mirò.", dataInzio:"2023/12/26", dataFine:"2024/05/05"},
    {nome:"MOSTRA DI PICASSO AL MUDEC DI MILANO",artisti:"Pablo Picasso",immagine:"https://svetslik.si/wp-content/uploads/2021/09/Pablo-Picasso.jpg.webp", descrizione:"La mostra di Picasso al Mudec di Milano è dedicata al tema “La metamorfosi della figura”, con lo scopo di approfondire aspetti poco conosciuti della poetica del grande artista del Novecento, al fine di comprendere a fondo il valore del contributo artistico che il pittore spagnolo ancora esercita sull'arte contemporanea.", dataInzio:"2024/02/22", dataFine:"2024/07/30"},
    {nome:"MOSTRA 'CÉZANNE E RENOIR' A MILANO",artisti:"Paul Cézann e Pierre-Auguste Renoir",immagine:"https://www.gedistatic.it/content/gnn/img/lastampa/2024/03/18/180119354-34dbd6c3-f19f-4ec0-9873-9b62f28c3896.jpg", descrizione:"La mostra 'Cézanne e Renoir' in programma a Palazzo Reale dal 19 marzo 2024 porta a Milano una ricca selezione di opere provenienti da due prestigiosi musei parigini, il Museo d'Orsay e l'Orangerie, grazie alle quali sarà possibile ripercorrere la rivoluzionaria stagione artistica dell'Impressionismo e illustrare l'eredità pittorica lasciata dai due grandi maestri francesi alle avanguardie del Novecento.", dataInzio:"2024/03/19", dataFine:"2024/06/30"},
    {nome:"MOSTRA DI MUNCH A MILANO",artisti:"Edvard Munch",immagine:"https://cdn.mediatheque.epmoo.fr/link/pcp19ipc0ez0bz4.jpg", descrizione:"La mostra di Edvard Munch a Palazzo Reale di Milano offre l'imperdibile occasione di approfondire la conoscenza di uno dei più importanti interpreti della pittura europea a cavallo tra XIX e XX secolo, che ha saputo rielaborare gli stimoli della pittura del proprio tempo dando vita a un'arte personalissima ma al contempo in grado di rappresentare le angosce e le paure del genere umano.", dataInzio:"2024/10/01", dataFine:"2025/01/10"},
  ]
  dati=[
    {nome:'MOSTRA DI DE NITTIS A MILANO',immagine:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2MFvH7vgqnmmcFe2eOyZkb4SumfVIhnkfxszPy3i6WQ&s",descrizione:"La visita guidata alla mostra di De Nittis a Milano, ospitata nelle sale di Palazzo Reale, è un'immersione nelle atmosfere colorate e luminose di uno dei più grandi pittori italiani dell'Ottocento.\nE Attraverso un esposizione di oltre 100 opere, in alcuni casi inedite, sarà possibile ripercorre l intera e fortunata carriera del celebre pittore di Barletta, dagli esordi fino al suo contatto con i Macchiaioli a Firenze, dal sodalizio con gli Impressionisti a Parigi fino ai fecondi scambi con il mondo letterario dell'epoca, dal periodo londinese fino alla morte prematura, avvenuta a soli 38 anni.\nE I colori accesi e le luci della pittura en plein air consentono a De Nittis di raffigurare in maniera unica sia i paesaggi innevati sia l energia solare dei campi in fiore, di penetrare la psicologia dei personaggi ritratti e insieme restituire con estrema freschezza la vibrazione delle scene di vita quotidiana, senza mai rinunciare a imprimere, nelle sue opere, quella malinconia soffusa e quel febbrile entusiasmo di un epoca sottilmente in bilico tra passato e presente.\nE La pittura di De Nittis, troppo spesso e troppo riduttivamente definito un impressionista italiano, rivela invece la sensibilità unica di un giovane talentuoso, che sfuggendo dal provincialismo della propria terra di origine, seppe elaborare un linguaggio peculiare e originale, coniugando le più diverse influenze stilistiche e le più disparate suggestioni, fino ad essere riconosciuto a livello internazionale ed apprezzato dal collezionismo contemporaneo e successivo.\nE La mostra di de Nittis a Milano sarà dunque un occasione per entrare nel mondo allegro, luminoso e spensierato di uno dei più grandi interpreti della pittura italiana, cogliendone le relazioni, le peculiarità e l eccezionalità che lo hanno reso famoso in tutto il mondo."},
    {nome:'MOSTRA DI MARTIN PARR A MILANO',immagine:"https://www.mudec.it/wp-content/uploads/2024/01/MARTIN_PARR_2280x1080-min.png",descrizione:"La visita guidata alla mostra di Martin Parr al Mudec di Milano ci porterà alla scoperta della visione sarcastica e anche politicamente scorretta di uno dei più celebri fotografi contemporanei, che ha saputo donare ai suoi scatti un tocco stravagante, mostrando i difetti della società senza alcun filtro morale.\nE L'analisi fotografica di Martin Parr inizia con i soggetti a lui più vicini, la media borghesia londinese, della quale inizia a contestare i gusti e le abitudini. Dopo i primi scatti in bianco e nero, il fotografo cambia completamente rotta passando alla realizzazione di fotografie dai colori vividi e dai forti contrasti tra luci e ombre, mischiando elementi della realtà con espedienti artificiali. I temi affrontati e criticati in vena ironica riguardano soprattutto i mali della società: il cibo, il turismo di massa, il consumismo, la vanità e l'inseguimento delle mode.\nE La mostra del Mudec di Milano presenta oltre duecento scatti, che compongono una panoramica completa dei capolavori del fotografo. La visita guidata esplorerà anche il mondo più intimo della vita e dell'evoluzione espressiva di Martin Parr, raccontando anche l'uomo che si cela dietro a quegli scatti formalmente irriverenti e stilisticamente originali che formano un mosaico complesso e ben costruito della poetica di Parr.\nE La visita guidata alla mostra di Martin Parr a Milano da un lato evidenzierà l originalità stilistica di un grande fotografo che con i suoi scatti, ricchi di creatività ed ironia, ha saputo rendere l ordinario qualcosa di straordinario, dall'altro ci permetterà di osservare in modo inedito e bizzarro la società contemporanea della quale anche noi facciamo parte."},
    {nome:'TATUAGGIO. STORIE DAL MEDITERRANEO',immagine:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIAiFrv-c0od3pbvE7Iu-1Z8NVcdjWOyd-9OZciDZuzQ&s",descrizione:" La visita guidata alla mostra 'Tatuaggio. Storie dal Mediterraneo' ospitata dal Mudec a Milano è un viaggio nel tempo alla scoperta di una pratica artistica, molto in voga ai giorni nostri ma nata nella remota preistoria, con un focus geografico posto sull'Italia e sull'area del Mediterraneo.\nE Reperti, riproduzioni di filmati e proiezioni di fotografie scandiranno il percorso espositivo tra i vari secoli, che ci permetterà di comprendere a fondo le modalità di esecuzione e i vari significati che venivano e che vengono tutt'oggi attributi ai disegni realizzati sul corpo. Un'esperienza intensa che avrà inizio da Ötzi, il primo essere umano tatuato conosciuto e che terminerà affrontando il grande significato del tatuaggio spirituale per le donne curde presenti nei campi profughi siriani.\nE Scopriremo che il tatuaggio non è un semplice decoro estetico, ma una pratica che racchiude numerosi significati che si sono arricchiti nei vari secoli in concomitanza con le vicende storiche: veniva usato per identificare un certo status di appartenenza, anche in modo forzato, come capitava agli schiavi o a persone che avevano disonorato i propri doveri o la famiglia, per scopi terapeutici o per marcare un certo legame con un credo religioso o una forza spirituale.\nE La visita guidata dedicata alla mostra 'Tatuaggio. Storie dal Mediterraneo' è un'occasione interessante per scoprire l'evoluzione di questa particolare pratica di colorazione della pelle che racchiude in sé una storia antica e contemporanea ancora tutta da esplorare."},
    {nome:'MOSTRA JOAN MIRÒ. LA POESIA DELLE FORME A MONZA',immagine:"https://www.lafeltrinelli.it/assets/2024/01/20240102110927-miro-.png",descrizione:"La visita guidata alla mostra di Joan Mirò a Monza, allestita al terzo piano del Belvedere alla Villa Reale, sarà un'occasione unica per conoscere da vicino la produzione artistica, variegata, sperimentale e bizzarra, di uno degli artisti più versatili del Novecento.\nE Il percorso espositivo, composto da oltre cento opere, tra cui dipinti, incisioni e libri illustrati racconta la vita e la carriera dell'artista catalano, soffermandosi su uno dei temi a lui più cari: il rapporto costante e inscindibile tra immagine e testo, tra arte e letteratura. L'attenzione è posta sulla passione per la letteratura e sul rapporto di grande amicizia che costruì nell'arco della propria carriera con numerosi scrittori, poeti ed editori europei, rivelando così un lato intimo e personale della sua esistenza.\nE Tra le opere presenti in mostra è possibile ricercare i numerosi rimandi captati da Mirò nei suoi anni parigini a contatto con le opere dei più grandi artisti dell'Ottocento e delle Avanguardie, tra cui i Fauves, Vincent Van Gogh, Pablo Picasso, Max Ernst, il Dadaismo e il Surrealismo. Il linguaggio artistico di Mirò, costantemente arricchito da contatti e suggestioni estetiche di grande valore, divenne unico e si caratterizzò con la presenza di forme essenziali e di simboli universalmente comprensibili, che abitano uno spazio onirico in una perfetta armonia di forme, colori e composizioni.\nE La mostra si conclude con un viaggio immersivo nell'arte di Mirò, un'esperienza virtuale ricca di emozioni e significati, in cui il visitatore sembra galleggiare tra forme fantastiche, colori sgargianti e figure bizzarre.\nE La visita guidata alla mostra di Mirò a Monza permette di approfondire il legame dell'artista catalano con la letteratura e di conoscere da vicino la sua grande capacità di sperimentare stili e tecniche pittoriche molto diverse tra loro. "},
    {nome:'TATUAGGIO. STORIE DAL MEDITERRANEO',immagine:"",descrizione:""},
    {nome:'TATUAGGIO. STORIE DAL MEDITERRANEO',immagine:"",descrizione:""},
    {nome:'TATUAGGIO. STORIE DAL MEDITERRANEO',immagine:"",descrizione:""},
  ]
  
}
